exports.morse = text =>
  text
    .replace(/a/gi, '😄 🍆') //· -
    .replace(/b/gi, '🍆 😄 😄 😄')
    .replace(/c/gi, '🍆 😄 🍆 😄')
    .replace(/d/gi, '🍆 😄 😄')
    .replace(/e/gi, '😄')
    .replace(/f/gi, '😄 😄 🍆 😄')
    .replace(/g/gi, '🍆 🍆 😄')
    .replace(/h/gi, '😄 😄 😄 😄')
    .replace(/i/gi, '😄 😄')
    .replace(/j/gi, '😄 🍆 🍆 🍆')
    .replace(/k/gi, '🍆 😄 🍆')
    .replace(/l/gi, '😄 🍆 😄 😄')
    .replace(/m/gi, '🍆 🍆')
    .replace(/n/gi, '🍆 😄')
    .replace(/o/gi, '🍆 🍆 🍆')
    .replace(/p/gi, '😄 🍆 🍆 😄')
    .replace(/q/gi, '🍆 🍆 😄 🍆')
    .replace(/r/gi, '😄 🍆 😄')
    .replace(/s/gi, '😄 😄 😄')
    .replace(/t/gi, '🍆')
    .replace(/u/gi, '😄 😄 🍆')
    .replace(/v/gi, '😄 😄 😄 🍆')
    .replace(/w/gi, '😄 🍆 🍆')
    .replace(/x/gi, '🍆 😄 😄 🍆')
    .replace(/y/gi, '🍆 😄 🍆 🍆')
    .replace(/z/gi, '🍆 🍆 😄 😄')
    .replace(/1/gi, '😄 🍆 🍆 🍆 🍆')
    .replace(/2/gi, '😄 😄 🍆 🍆 🍆')
    .replace(/3/gi, '😄 😄 😄 🍆 🍆')
    .replace(/4/gi, '😄 😄 😄 😄 🍆')
    .replace(/5/gi, '😄 😄 😄 😄 😄')
    .replace(/6/gi, '🍆 😄 😄 😄 😄')
    .replace(/7/gi, '🍆 🍆 😄 😄 😄')
    .replace(/8/gi, '🍆 🍆 🍆 😄 😄')
    .replace(/9/gi, '🍆 🍆 🍆 🍆 😄')
    .replace(/0/gi, '🍆 🍆 🍆 🍆 🍆')